"""Generating reports, recording them, and checking copies later.

Exporting a report is data leaving SentinelFlow, so every export is audited:
who generated it, in which format, through which channel, and the SHA-256 of
the exact bytes produced. The report carries its own ID, so a copy found
later - attached to a ticket, forwarded by e-mail - can be checked:

* **verified**: the file is byte-for-byte what SentinelFlow produced;
* **modified**: SentinelFlow produced a report with that ID, but not this one;
* **unknown**: no report with that ID was ever recorded here.

The hash cannot be printed inside the file it describes, which is why it lives
in the audit trail and the file carries only the ID.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from enum import StrEnum
from typing import Any
from uuid import UUID

from sqlalchemy.orm import Session

from app import __version__
from app.database import repository
from app.models.analyst import AuditEntry
from app.models.enums import Actor, AuditAction
from app.reports.html import render_html
from app.reports.markdown import render_markdown
from app.reports.model import (
    Report,
    ReportKind,
    build_alert_report,
    build_incident_report,
)
from app.services.workflow import Channel

REPORT_ID_RE = re.compile(r"\bSFR-\d{8}-[0-9a-f]{8}\b")


class ReportFormat(StrEnum):
    MARKDOWN = "markdown"
    HTML = "html"
    JSON = "json"

    @property
    def extension(self) -> str:
        return {"markdown": "md", "html": "html", "json": "json"}[self.value]

    @property
    def media_type(self) -> str:
        return {
            "markdown": "text/markdown; charset=utf-8",
            "html": "text/html; charset=utf-8",
            "json": "application/json",
        }[self.value]


@dataclass(frozen=True)
class GeneratedReport:
    report_id: str
    kind: ReportKind
    subject_id: UUID
    format: ReportFormat
    content: bytes
    sha256: str

    @property
    def filename(self) -> str:
        return (
            f"sentinelflow-{self.kind}-{str(self.subject_id)[:8]}-{self.report_id}"
            f".{self.format.extension}"
        )


class VerificationStatus(StrEnum):
    VERIFIED = "verified"
    MODIFIED = "modified"
    UNKNOWN = "unknown"
    NO_ID = "no_id"


@dataclass(frozen=True)
class Verification:
    status: VerificationStatus
    sha256: str
    report_id: str | None = None
    recorded: AuditEntry | None = None

    @property
    def message(self) -> str:
        if self.status is VerificationStatus.VERIFIED and self.recorded is not None:
            who = self.recorded.actor_name or "an analyst"
            return (
                f"Verified: this is report {self.report_id} exactly as SentinelFlow generated "
                f"it for {who} on {self.recorded.occurred_at:%Y-%m-%d %H:%M} UTC."
            )
        if self.status is VerificationStatus.MODIFIED:
            return (
                f"Modified: SentinelFlow generated report {self.report_id}, but not this file. "
                "Its content differs from what was recorded."
            )
        if self.status is VerificationStatus.UNKNOWN:
            return f"Unknown: no report {self.report_id} was ever generated by this SentinelFlow."
        return "No SentinelFlow report ID was found in this file."


class ReportService:
    def __init__(self, session: Session, *, analyst: str, channel: Channel) -> None:
        self.session = session
        self.analyst = analyst
        self.channel = channel

    def generate(
        self, kind: ReportKind, subject_id: UUID, report_format: ReportFormat
    ) -> GeneratedReport:
        """Build, render, fingerprint and audit one report."""
        build = build_incident_report if kind == "incident" else build_alert_report
        report = build(self.session, subject_id, generated_by=self.analyst)
        content = render(report, report_format).encode("utf-8")
        digest = hashlib.sha256(content).hexdigest()
        repository.record_audit(
            self.session,
            AuditEntry(
                actor=Actor.ANALYST,
                actor_name=self.analyst,
                action=AuditAction.REPORT_GENERATED,
                object_type=kind,
                object_id=subject_id,
                after=f"report {report.report_id} sha256:{digest}",
                detail=f"format={report_format.value} via {self.channel.value}",
            ),
        )
        return GeneratedReport(
            report_id=report.report_id,
            kind=kind,
            subject_id=subject_id,
            format=report_format,
            content=content,
            sha256=digest,
        )


def render(report: Report, report_format: ReportFormat) -> str:
    if report_format is ReportFormat.MARKDOWN:
        return render_markdown(report)
    if report_format is ReportFormat.HTML:
        return render_html(report)
    return json.dumps(to_json(report), indent=2, ensure_ascii=False) + "\n"


def verify_report(session: Session, content: bytes) -> Verification:
    """Check a report file against the fingerprint recorded when it was generated."""
    digest = hashlib.sha256(content).hexdigest()
    match = REPORT_ID_RE.search(content.decode("utf-8", errors="replace"))
    if match is None:
        return Verification(VerificationStatus.NO_ID, digest)
    report_id = match.group(0)
    recorded = [
        entry
        for entry in repository.list_audit(
            session, action=AuditAction.REPORT_GENERATED, limit=100_000
        )
        if (entry.after or "").startswith(f"report {report_id} ")
    ]
    if not recorded:
        return Verification(VerificationStatus.UNKNOWN, digest, report_id)
    entry = recorded[0]
    status = (
        VerificationStatus.VERIFIED
        if entry.after == f"report {report_id} sha256:{digest}"
        else VerificationStatus.MODIFIED
    )
    return Verification(status, digest, report_id, entry)


def to_json(report: Report) -> dict[str, Any]:
    """A machine-readable report for tickets and automation.

    Values are raw, not defanged: a consumer of JSON is a program that needs
    the real indicator. ``raw_event`` is omitted, as in every other format.
    """
    return {
        "sentinelflow_version": __version__,
        "report_id": report.report_id,
        "kind": report.kind,
        "subject_id": str(report.subject_id),
        "title": report.title,
        "generated_at": report.generated_at.isoformat(),
        "generated_by": report.generated_by,
        "state": report.state_label,
        "reviewed_by_analyst": report.reviewed,
        "severity": {"level": report.severity.value, "score": report.top_score},
        "summary": report.summary_sentences(),
        "conclusion": report.conclusion(),
        "hostnames": report.hostnames,
        "usernames": report.usernames,
        "window": [t.isoformat() for t in report.window] if report.window else None,
        "incident": report.incident.model_dump(mode="json") if report.incident else None,
        "alerts": [
            {
                "alert": section.alert.model_dump(mode="json"),
                "event": section.event.model_dump(mode="json", exclude={"raw_event"})
                if section.event
                else None,
                "ai_analyses": [a.model_dump(mode="json") for a in section.analyses],
                "notes": [n.model_dump(mode="json") for n in section.notes],
            }
            for section in report.alerts
        ],
        "incident_notes": [n.model_dump(mode="json") for n in report.incident_notes],
        "techniques": [
            {
                "technique_id": use.technique.technique_id,
                "name": use.technique.name,
                "tactics": use.technique.tactics,
                "reasons": use.reasons,
            }
            for use in report.techniques
        ],
        "indicators": [
            {**i.model_dump(mode="json"), "scope": _scope(i.is_internal, i.is_documentation)}
            for i in report.indicators
        ],
        "recommendations": [
            {"rule_id": rule_id, "text": text} for rule_id, text in report.recommendations
        ],
        "history": [e.model_dump(mode="json") for e in report.history],
        "history_truncated": report.history_truncated,
        "limitations": report.limitations(),
    }


def _scope(internal: bool, documentation: bool) -> str:
    return "internal" if internal else "documentation" if documentation else "external"
