"""Optional AI analysis — advisory output, structurally kept in its place.

This module is where the project's central claim becomes code. Everything the
model produces lands in :class:`AIAnalysis`, and that class is built so it
cannot be mistaken for, or substituted for, a deterministic result:

* **There is no field named ``severity``.** The model may offer
  ``suggested_severity``, which is a different name, on a different object, in
  a different table. :class:`~app.models.alert.AlertSeverity` — the real
  verdict — is a structured type this value cannot be assigned to.
* **``is_advisory`` is a constant ``True``** that travels with the record into
  the database, the API and the report. There is no serialisation path where
  the label gets lost.
* **Every claim must be labelled** ``OBSERVED``, ``INFERRED`` or ``UNKNOWN``.
  A model that states a guess as a fact is producing invalid output, and it is
  rejected at the schema boundary rather than shown to an analyst.
* **``injection_suspected``** records that the evidence contained something
  that looked like an attempt to steer the model. Event data is attacker-
  controlled text; treating that as a first-class possibility rather than an
  edge case is the point.

None of this makes a language model trustworthy. It makes the *system* safe to
use with an untrustworthy component in it.
"""

from __future__ import annotations

from typing import Any, ClassVar, Literal
from uuid import UUID

from pydantic import Field, field_validator, model_validator

from app.core.sanitize import clean_line, clean_text
from app.models.base import EvidenceModel, UtcDatetime, new_id, utcnow
from app.models.enums import Severity, StatementType

#: Bounds on model output. A local model can loop; these caps make that a
#: truncated analysis rather than an unbounded write to the database.
MAX_STATEMENTS = 40
MAX_LIST_ENTRIES = 20
MAX_ENTRY_LENGTH = 1_024
MAX_SUMMARY_LENGTH = 4_096


class AIStatement(EvidenceModel):
    """A single labelled claim from the model."""

    statement_type: StatementType
    text: str = Field(min_length=1, max_length=MAX_ENTRY_LENGTH)

    @field_validator("text", mode="before")
    @classmethod
    def _clean(cls, value: Any) -> str:
        text = clean_text(value, max_length=MAX_ENTRY_LENGTH)
        if not text:
            raise ValueError("a statement cannot be empty")
        return text

    def __str__(self) -> str:
        return f"{self.statement_type.value.upper()}: {self.text}"


class AIAnalysis(EvidenceModel):
    """An advisory analysis of an alert, produced by a local model.

    Absent when AI is disabled, which is the default. Nothing downstream may
    require this object to exist.
    """

    DISCLAIMER: ClassVar[str] = (
        "AI SUGGESTION - NOT AUTHORITATIVE. Generated by a language model from the "
        "evidence below. It may be incomplete or wrong, and it did not influence the "
        "deterministic severity, the detections or the MITRE mappings shown on this alert."
    )

    # --- Identity -------------------------------------------------------
    analysis_id: UUID = Field(default_factory=new_id)
    alert_id: UUID
    generated_at: UtcDatetime = Field(default_factory=utcnow)

    # --- Provenance -----------------------------------------------------
    provider: str = Field(max_length=64, description="e.g. 'ollama'.")
    model: str = Field(max_length=128, description="e.g. 'llama3.1:8b'.")
    duration_ms: int | None = Field(default=None, ge=0)
    prompt_version: str | None = Field(default=None, max_length=32)

    # --- Content --------------------------------------------------------
    summary: str = Field(max_length=MAX_SUMMARY_LENGTH)
    statements: list[AIStatement] = Field(default_factory=list, max_length=MAX_STATEMENTS)
    suspicious_observations: list[str] = Field(default_factory=list, max_length=MAX_LIST_ENTRIES)
    possible_explanations: list[str] = Field(default_factory=list, max_length=MAX_LIST_ENTRIES)
    analyst_questions: list[str] = Field(default_factory=list, max_length=MAX_LIST_ENTRIES)
    recommended_next_steps: list[str] = Field(default_factory=list, max_length=MAX_LIST_ENTRIES)

    # --- Advisory severity ----------------------------------------------
    suggested_severity: Severity | None = Field(
        default=None,
        description=(
            "The model's opinion. Displayed beside the deterministic severity and "
            "clearly labelled. It is never copied into the alert."
        ),
    )
    suggested_severity_rationale: str | None = Field(default=None, max_length=MAX_ENTRY_LENGTH)

    # --- Safety flags ----------------------------------------------------
    is_advisory: Literal[True] = Field(
        default=True, description="Constant. Marks this record as non-authoritative."
    )
    injection_suspected: bool = Field(
        default=False,
        description="Set when the evidence contained apparent instructions to the model.",
    )
    truncated: bool = Field(
        default=False, description="Set when model output exceeded the size limits."
    )

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    @model_validator(mode="before")
    @classmethod
    def _bound_output_size(cls, data: Any) -> Any:
        """Cap over-long model output and record that it happened.

        A local model that loops produces hundreds of near-identical bullet
        points. Rejecting the whole analysis would throw away the useful part,
        so the lists are capped instead — and ``truncated`` is set, because an
        analyst reading a shortened analysis needs to know it was shortened.
        """
        if not isinstance(data, dict):
            return data
        caps = {
            "statements": MAX_STATEMENTS,
            "suspicious_observations": MAX_LIST_ENTRIES,
            "possible_explanations": MAX_LIST_ENTRIES,
            "analyst_questions": MAX_LIST_ENTRIES,
            "recommended_next_steps": MAX_LIST_ENTRIES,
        }
        truncated = bool(data.get("truncated", False))
        for name, cap in caps.items():
            value = data.get(name)
            if isinstance(value, list) and len(value) > cap:
                data[name] = value[:cap]
                truncated = True
        data["truncated"] = truncated
        return data

    @field_validator("provider", "model", mode="before")
    @classmethod
    def _require_provenance(cls, value: Any) -> str:
        text = clean_line(value, max_length=128)
        if not text:
            raise ValueError("AI output must record which provider and model produced it")
        return text

    @field_validator("summary", mode="before")
    @classmethod
    def _clean_summary(cls, value: Any) -> str:
        text = clean_text(value, max_length=MAX_SUMMARY_LENGTH)
        if not text:
            raise ValueError("summary is required")
        return text

    @field_validator(
        "suspicious_observations",
        "possible_explanations",
        "analyst_questions",
        "recommended_next_steps",
        mode="before",
    )
    @classmethod
    def _clean_entries(cls, value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            value = [value]
        cleaned = [clean_text(item, max_length=MAX_ENTRY_LENGTH) for item in value]
        return [item for item in cleaned if item]

    @field_validator("suggested_severity_rationale", "prompt_version", mode="before")
    @classmethod
    def _clean_optional(cls, value: Any) -> str | None:
        return clean_text(value, max_length=MAX_ENTRY_LENGTH)

    # ------------------------------------------------------------------
    # Reading the analysis
    # ------------------------------------------------------------------
    def statements_of(self, statement_type: StatementType) -> list[AIStatement]:
        return [s for s in self.statements if s.statement_type is statement_type]

    @property
    def observed(self) -> list[AIStatement]:
        """Claims the model says are directly supported by the evidence."""
        return self.statements_of(StatementType.OBSERVED)

    @property
    def inferred(self) -> list[AIStatement]:
        """Hypotheses. Useful, unproven."""
        return self.statements_of(StatementType.INFERRED)

    @property
    def unknown(self) -> list[AIStatement]:
        """Open questions — in practice, the investigation's to-do list."""
        return self.statements_of(StatementType.UNKNOWN)

    @property
    def has_unsupported_confidence(self) -> bool:
        """True when the model asserted things without acknowledging any gaps.

        An analysis of a real alert that contains no ``UNKNOWN`` statements is
        suspicious: there is always something not in the logs. Surfaced in the
        UI as a nudge, not as a rejection.
        """
        return bool(self.statements) and not self.unknown
